# This is a basic workflow to help you get started with Actions

name: CI
on: [push]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world!"
